#!/usr/bin/env bash
# Copyright (c) 2026 Jurjen Stellingwerff
# SPDX-License-Identifier: LGPL-3.0-or-later
#
# PLAN-SCALE S1 — the step that gates every other step: does loft's WORKING-SET loader read a store over
# HTTP Range, and does it do so in the BROWSER (`loft --html`), which is where the app runs?
#
# Why this is a gate and not a note: PLAN-SCALE D3 makes loft's paged loader the entire WE read path (we
# never author a codec — a gap there is a loft bug to report, not to route around). Whether that path
# exists in wasm decides the rung order in §6b, so it must be re-checkable rather than remembered.
#
# Three cases, each with the SAME store and key, so the answers are comparable:
#   1. NATIVE, local file   — the baseline; proves the store + key + expected contents (also tools/paged_gate.sh)
#   2. NATIVE, http:// URL  — loft's HttpRangeProvider (src/paged_reader.rs, ureq) against a real Range server
#   3. BROWSER, http:// URL — the same program built with `loft --html`, driven headless
#
# Case 3 is the open question. In wasm there are no sockets: HTTP has to ride the asyncify `fetch()` bridge
# that `store_load_url_trusted` uses, and nothing in loft's browser docs mentions the paged loaders. A
# FAILURE here is a legitimate, expected outcome and is REPORTED, not worked around: this script's output is
# the reproducer for the upstream issue.
#
#   tools/paged_http_gate.sh            # exit 0 = native http works AND browser status is recorded
#   BROWSER_REQUIRED=1 tools/paged_http_gate.sh   # additionally FAIL if the browser case does not work
set -uo pipefail
here="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
loft="${LOFT_BIN:-$(command -v loft || echo /usr/local/bin/loft)}"
port="${PORT:-8797}"
work="$(mktemp -d)"
chrome="$(command -v chromium-browser || command -v chromium || command -v google-chrome || echo chromium)"
store_src="$here/browser/stores/enschede.roads.store"
trap 'kill $srv 2>/dev/null; rm -rf "$work"' EXIT
[ -f "$store_src" ] || { echo "SKIP: no roads store at $store_src"; exit 2; }

cp "$store_src" "$work/block.store"
[ -f "$store_src.dschema" ] && cp "$store_src.dschema" "$work/block.store.dschema"

# The key: a tile that really carries roads, found by the native local-file path. An absent key returns
# false exactly like a refusal, so probing a key that is not there would prove nothing.
cat > "$work/pick.loft" <<'LOFT'
#cwd
use routing_kernel::TTile;
fn main() {
  a: vector<text> = [];
  for x in arguments() { a += [x]; }
  tiles: hash<TTile[tkey]> = [];
  store_load(tiles, a[0] ?? "");
  best = 0; best_n = 0;
  for t in tiles { if len(t.roads) > best_n { best_n = len(t.roads); best = t.tkey; } }
  println("KEY {best} ROADS {best_n}");
}
LOFT
pick="$("$loft" --native --lib "$here/lib" "$work/pick.loft" "$work/block.store" 2>/dev/null | grep '^KEY ')" \
  || { echo "FAIL: could not pick a key"; exit 1; }
key="$(echo "$pick" | awk '{print $2}')"
want_roads="$(echo "$pick" | awk '{print $4}')"
echo "== S1: working-set load over HTTP Range =="
echo "  store: $(stat -c%s "$work/block.store") bytes · probing tkey=$key (expect roads=$want_roads)"

# One program, three ways to run it. The source is generated so the URL is baked in: a `--html` build has
# no argv, and plumbing input would add a failure mode to the thing under test.
gen_probe() {  # $1 = source path ("" = local file), $2 = out file
  cat > "$2" <<LOFT
#cwd
use routing_kernel::TTile;
// PLAN-SCALE S1 probe (generated by tools/paged_http_gate.sh). Loads ONE tile by key and reports what
// came back, so native-local, native-http and browser-http answers are directly comparable.
fn main() {
  ws: hash<TTile[tkey]> = [];
  ok = store_load_key(ws, "$1", $key);
  n = 0; roads = 0; steps = 0;
  for t in ws { n += 1; roads += len(t.roads); steps += len(t.steps); }
  println("RESULT ok={ok} entries={n} roads={roads} steps={steps}");
  if ok && n == 1 && roads == $want_roads { println("VERDICT PASS"); } else { println("VERDICT FAIL"); }
}
LOFT
}

url="http://127.0.0.1:$port/block.store"
gen_probe "block.store" "$work/local.loft"
gen_probe "$url" "$work/remote.loft"

# --- 1. native, local file ------------------------------------------------------------------------
loc="$(cd "$work" && LOFT_LOADER_STATS=1 "$loft" --native --lib "$here/lib" "$work/local.loft" 2>&1)"
echo "  [1] native, local file : $(echo "$loc" | grep -E '^RESULT|^VERDICT' | tr '\n' ' ')"
echo "$loc" | grep -q '^VERDICT PASS' || { echo "$loc"; echo "FAIL: the local-file baseline broke"; exit 1; }

python3 "$here/tools/range_server.py" "$port" "$work" "$work/.report" >/dev/null 2>&1 &
srv=$!
for _ in $(seq 20); do curl -s -o /dev/null "http://127.0.0.1:$port/block.store" 2>/dev/null && break; sleep 0.3; done
rc206="$(curl -s -o /dev/null -w '%{http_code}' -H 'Range: bytes=0-0' "$url")"
echo "  range server: Range GET → HTTP $rc206"
[ "$rc206" = "206" ] || { echo "FAIL: server does not honour Range"; exit 1; }

# --- 2. native, http:// URL -----------------------------------------------------------------------
rem="$(cd "$work" && LOFT_LOADER_STATS=1 "$loft" --native --lib "$here/lib" "$work/remote.loft" 2>&1)"
echo "  [2] native, http Range : $(echo "$rem" | grep -E '^RESULT|^VERDICT' | tr '\n' ' ')"
echo "$rem" | grep -E 'store_load_keys|refusing' | sed 's/^/        /'
native_http=fail
echo "$rem" | grep -q '^VERDICT PASS' && native_http=pass

# --- 3. browser, http:// URL ----------------------------------------------------------------------
browser=unknown
if ! command -v "$chrome" >/dev/null 2>&1; then
  echo "  [3] browser            : SKIP (no chromium)"
else
  if ! "$loft" --html "$work/page.html" --lib "$here/lib" "$work/remote.loft" >"$work/build.log" 2>&1; then
    browser=build_failed
    echo "  [3] browser            : BUILD FAILED — $(tail -3 "$work/build.log" | tr '\n' ' ')"
  else
    cat > "$work/driver.html" <<'HTML'
<!doctype html><meta charset=utf-8><title>S1 paged-http driver</title>
<pre id=log>running…</pre>
<script>
const report = m => { document.getElementById('log').textContent = m;
                      fetch('/report?r=' + encodeURIComponent(m)).catch(()=>{}); };
window.addEventListener('error', e => report('winerror=' + (e.message || e)));
const f = document.createElement('iframe'); f.width = 700; f.height = 260; f.src = 'page.html';
document.body.appendChild(f);
setTimeout(() => {
  try {
    const d = f.contentDocument;
    report('OUT<<' + (d.getElementById('out') || d.body).textContent.replace(/\s+/g,' ').trim() + '>>');
  } catch (e) { report('driver_error=' + (e.message || e)); }
}, 12000);
</script>
HTML
    : > "$work/.report"
    timeout 90 "$chrome" --headless=new --no-sandbox --disable-gpu \
      "http://127.0.0.1:$port/driver.html" >/dev/null 2>&1 &
    ch=$!
    for _ in $(seq 30); do [ -s "$work/.report" ] && break; sleep 1; done
    kill $ch 2>/dev/null
    out="$(head -1 "$work/.report")"
    echo "  [3] browser, http Range: ${out:-(no report — the page never reported)}"
    case "$out" in
      *"VERDICT PASS"*) browser=pass ;;
      *"RESULT ok=false"*|*"RESULT ok=0"*) browser=refused ;;
      "") browser=no_report ;;
      *) browser=other ;;
    esac
  fi
fi

echo
echo "  S1 RESULT  native_http=$native_http  browser=$browser"
if [ "$native_http" != "pass" ]; then
  echo "FAIL: loft's own native HTTP Range path did not load the tile — that is the baseline for PLAN-SCALE D3."
  exit 1
fi
case "$browser" in
  pass) echo "PASS — the paged Range read works natively AND in the browser: PLAN-SCALE C1 is unblocked" ;;
  *)    echo "RECORDED — native Range works; the BROWSER path does not (browser=$browser)."
        echo "           PLAN-SCALE §2/§8 Q1: this is the upstream ask (paged loaders over the asyncify"
        echo "           fetch bridge), with this script as the reproducer. Not something to work around here."
        [ "${BROWSER_REQUIRED:-0}" = "1" ] && exit 1 ;;
esac
exit 0
